**Importing the Datafile**

In [1]:
# import appropriate packages
import numpy as np
import pandas as pd

In [2]:
# read the excel file
# had to install the xlrd package to read the file 
df = pd.read_csv("csv_files/clean_data_kerry.csv", index_col=0)
df.head(10)

,I1,I2,I3,P(IPO),P(H),P(L),P(1Day),C1,C2,C3,...,T5,S1,S2,S3,P(mid),Y1,Y2,C3p,C5p,C6p
0,AATI,ADVANCED ANALOGIC TECHNOLOGIES INC,3674,10.0,9.5,8.5,11.870000,122.0,1.0,3.43,...,690.0,62.0,117.0,139.0,9.0,0,1,0,3.864345,11.111111
1,ABPI,ACCENTIA BIOPHARMACEUTICALS INC,2834,8.0,10.0,8.0,7.250000,259.0,0.0,-1.62,...,1120.0,71.0,242.0,237.0,9.0,1,0,1,12.028832,0.000000
2,ACAD,ACADIA PHARMACEUTICALS INC,2834,7.0,14.0,12.0,6.700000,90.0,1.0,-1.24,...,325.0,61.0,33.0,60.0,13.0,1,0,1,3.369134,0.000000
3,ACHN,ACHILLION PHARMACEUTICALS INC,2834,11.5,16.0,14.0,12.390000,209.0,1.0,-0.91,...,509.0,80.0,59.0,110.0,15.0,1,1,1,3.299697,0.000000
4,ACLI,AMERICAN COMMERCIAL LINES INC.,4492,21.0,21.0,19.0,56.599998,80.0,1.0,0.07,...,720.0,67.0,149.0,167.0,20.0,0,1,0,3.726269,5.000000
5,ACOM,Ancestry.com Inc.,7379,13.5,14.5,12.5,14.200000,94.0,1.0,0.06,...,815.0,62.0,96.0,181.0,13.5,0,1,0,5.724394,0.000000
6,ACOR,ACORDA THERAPEUTICS INC,2836,6.0,13.0,11.0,6.720000,128.0,1.0,-1.87,...,698.0,82.0,106.0,135.0,12.0,1,1,1,3.463095,0.000000
7,ACRX,ACELRX PHARMACEUTICALS INC,2834,5.0,14.0,12.0,4.550000,91.0,0.0,-0.74,...,-1.0,55.0,120.0,122.0,13.0,1,0,1,2.421469,0.000000
8,ACTV,ACTIVE NETWORK INC,7372,15.0,18.0,16.0,15.900000,100.0,1.0,-0.51,...,917.0,58.0,124.0,234.0,17.0,1,1,1,4.816591,0.000000
9,ACW,ACCURIDE CORP,3714,9.0,19.0,17.0,0.000000,106.0,1.0,1.49,...,459.0,81.0,90.0,147.0,18.0,1,0,0,3.056608,0.000000

In [3]:
# replace '-' with NaN (smooth the data)
df.replace(to_replace='-', value=np.nan, inplace=True)
df.head(12)

,I1,I2,I3,P(IPO),P(H),P(L),P(1Day),C1,C2,C3,...,T5,S1,S2,S3,P(mid),Y1,Y2,C3p,C5p,C6p
0,AATI,ADVANCED ANALOGIC TECHNOLOGIES INC,3674,10.000000,9.50000,8.500000,11.870000,122.000000,1.000000,3.430000,...,690.0,62.0,117.0,139.0,9.000000,0,1,0,3.864345,11.111111
1,ABPI,ACCENTIA BIOPHARMACEUTICALS INC,2834,8.000000,10.00000,8.000000,7.250000,259.000000,0.000000,-1.620000,...,1120.0,71.0,242.0,237.0,9.000000,1,0,1,12.028832,0.000000
2,ACAD,ACADIA PHARMACEUTICALS INC,2834,7.000000,14.00000,12.000000,6.700000,90.000000,1.000000,-1.240000,...,325.0,61.0,33.0,60.0,13.000000,1,0,1,3.369134,0.000000
3,ACHN,ACHILLION PHARMACEUTICALS INC,2834,11.500000,16.00000,14.000000,12.390000,209.000000,1.000000,-0.910000,...,509.0,80.0,59.0,110.0,15.000000,1,1,1,3.299697,0.000000
4,ACLI,AMERICAN COMMERCIAL LINES INC.,4492,21.000000,21.00000,19.000000,56.599998,80.000000,1.000000,0.070000,...,720.0,67.0,149.0,167.0,20.000000,0,1,0,3.726269,5.000000
5,ACOM,Ancestry.com Inc.,7379,13.500000,14.50000,12.500000,14.200000,94.000000,1.000000,0.060000,...,815.0,62.0,96.0,181.0,13.500000,0,1,0,5.724394,0.000000
6,ACOR,ACORDA THERAPEUTICS INC,2836,6.000000,13.00000,11.000000,6.720000,128.000000,1.000000,-1.870000,...,698.0,82.0,106.0,135.0,12.000000,1,1,1,3.463095,0.000000
7,ACRX,ACELRX PHARMACEUTICALS INC,2834,5.000000,14.00000,12.000000,4.550000,91.000000,0.000000,-0.740000,...,-1.0,55.0,120.0,122.0,13.000000,1,0,1,2.421469,0.000000
8,ACTV,ACTIVE NETWORK INC,7372,15.000000,18.00000,16.000000,15.900000,100.000000,1.000000,-0.510000,...,917.0,58.0,124.0,234.0,17.000000,1,1,1,4.816591,0.000000
9,ACW,ACCURIDE CORP,3714,9.000000,19.00000,17.000000,0.000000,106.000000,1.000000,1.490000,...,459.0,81.0,90.0,147.0,18.000000,1,0,0,3.056608,0.000000
10,ADKU,"ADCARE HEALTH SYSTEMS, INC",NaN,13.837666,15.48119,13.515045,25.934766,149.728788,0.859091,1.788904,...,263.0,51.0,65.0,74.0,14.498118,1,1,0,3.975593,0.000000
11,ADLS,"Advanced Life Sciences Holdings, Inc.",2854,5.000000,9.00000,8.000000,6.000000,99.000000,1.000000,-398.100000,...,385.0,29.0,41.0,70.0,8.500000,1,1,1,2.546686,0.000000

In [4]:
# exmaining the columns
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 682 entries, 0 to 681
Data columns (total 28 columns):
I1         682 non-null object
I2         682 non-null object
I3         674 non-null object
P(IPO)     682 non-null float64
P(H)       682 non-null float64
P(L)       682 non-null float64
P(1Day)    682 non-null float64
C1         682 non-null float64
C2         682 non-null float64
C3         682 non-null float64
C4         682 non-null float64
C5         682 non-null float64
C6         682 non-null float64
C7         682 non-null float64
T1         682 non-null float64
T2         682 non-null float64
T3         682 non-null float64
T4         682 non-null float64
T5         682 non-null float64
S1         682 non-null float64
S2         682 non-null float64
S3         682 non-null float64
P(mid)     682 non-null float64
Y1         682 non-null int64
Y2         682 non-null int64
C3p        682 non-null int64
C5p        682 non-null float64
C6p        682 non-null float64
dtypes: float64(22), int64(3), object(3)
memory usage: 154.5+ KB

**Creating Target Variables**

In [5]:
# Define a pmid column to utilize later
def Pmid(row):
    return (row['P(H)'] + row['P(L)'])/2

# add a new column with the values returned from the previous function
df['Pmid'] = df.apply(lambda row: Pmid(row),axis=1)

In [6]:
# Define Pre-IPO Revision
def Y1Func(row):
    if row['P(IPO)'] < row['Pmid']:
        return 1
    return 0

# add a new column with the values returned from the previous function
df['Y1'] = df.apply(lambda row: Y1Func(row),axis=1)

In [7]:
# Define Post-IPO Initial Return
def Y2Func(row):
    if row['P(IPO)'] < row['P(1Day)']:
        return 1
    return 0
# add a new column with the values returned from the previous function
df['Y2'] = df.apply(lambda row: Y2Func(row),axis=1)

**Creating Control Variables**

In [8]:
# Define Positive EPS Dummy
def C3pFunc(row):
    if row['C3'] > 0:
        return 1
    return 0
# add a new column with the values returned from the previous function
df['C3p'] = df.apply(lambda row: C3pFunc(row),axis=1)

In [9]:
# Define Share Overhang
def C5pFunc(row):
    return row['C5']/row['C6']
    
# add a new column with the values returned from the previous function
df['C5p'] = df.apply(lambda row: C5pFunc(row),axis=1)

In [10]:
# Define Up Revision
def C6pFunc(row):
    if row['P(IPO)'] > row['Pmid']:
        return 100*(row['P(IPO)']-row['Pmid'])/row['Pmid']
    return 0
    
# add a new column with the values returned from the previous function
df['C6p'] = df.apply(lambda row: C6pFunc(row),axis=1)

**Creating Ratio Variables**

In [11]:
# Define Long Sentences
def LongSentences(row):
    return row['T4']/row['T1']
    
# add a new column with the values returned from the previous function
df['LongSentences'] = df.apply(lambda row: LongSentences(row),axis=1)

In [12]:
# Define Real Words
def RealWords(row):
    if row['T2'] == 0 :
        return 0
    else: 
        return row['T3']/row['T2']

# add a new column with the values returned from the previous function
df['RealWords'] = df.apply(lambda row: RealWords(row),axis=1)

In [13]:
# Define Long Words
def LongWords(row):
    if row['T2'] == 0 :
        return 0
    else: 
        return row['T5']/row['T2']
    
# add a new column with the values returned from the previous function
df['LongWords'] = df.apply(lambda row: LongWords(row),axis=1)

In [14]:
# Define Positive Words
def PositiveWords(row):
    if row['T2'] == 0 :
        return 0
    else: 
        return row['S1']/row['T2']
    
# add a new column with the values returned from the previous function
df['PositiveWords'] = df.apply(lambda row: PositiveWords(row),axis=1)

In [15]:
# Define Negative Words
def NegativeWords(row):
    if row['T2'] == 0 :
        return 0
    else: 
        return row['S2']/row['T2']
    
# add a new column with the values returned from the previous function
df['NegativeWords'] = df.apply(lambda row: NegativeWords(row),axis=1)

In [16]:
# Define Uncertain Words
def UncertainWords(row):
    if row['T2'] == 0 :
        return 0
    else: 
        return row['S3']/row['T2']
    
# add a new column with the values returned from the previous function
df['UncertainWords'] = df.apply(lambda row: UncertainWords(row),axis=1)

In [17]:
df.sample(5)

,I1,I2,I3,P(IPO),P(H),P(L),P(1Day),C1,C2,C3,...,C3p,C5p,C6p,Pmid,LongSentences,RealWords,LongWords,PositiveWords,NegativeWords,UncertainWords
560,STRL,STERLING CONSTRUCTION CO INC,1600,15.0,15.48119,13.515045,25.934766,149.728788,0.859091,1.788904,...,1,5.038625,3.461708,14.498118,0.554839,0.888534,0.045170,0.006115,0.009034,0.011814
535,SIRT,"Sirtris Pharmaceuticals, Inc.",2834,10.0,11.00000,9.000000,10.760000,83.000000,1.000000,-0.620000,...,0,4.631519,0.000000,10.000000,0.579439,0.903603,0.054826,0.003615,0.007712,0.013255
563,SVR,SYNIVERSE HOLDINGS INC,4899,16.0,22.00000,20.000000,16.000000,90.000000,1.000000,-0.410000,...,0,3.840365,0.000000,21.000000,0.622059,0.877043,0.050048,0.004044,0.015672,0.009100
151,CSIQ,Canadian Solar Inc.,3674,15.0,15.00000,13.000000,15.630000,17.000000,1.000000,0.190000,...,1,3.541558,7.142857,14.000000,0.627941,0.908969,0.047081,0.006039,0.007437,0.009338
507,ROSG,Rosetta Genomics Ltd.,2834,7.0,8.50000,7.500000,439.200439,179.000000,1.000000,-40.800000,...,0,3.002746,0.000000,8.000000,0.695455,0.898924,0.059598,0.006370,0.006795,0.010900

**Normalizing the Data**

In [18]:
def normalize(col):
    mean = np.mean(col)
    low = min(col)
    high = max(col)
    colnorm = (col - mean) / (high - low)
    return colnorm

In [19]:
columns = ['P(IPO)', 'P(H)', 'P(L)', 'P(1Day)', 'C1', 'C3', 'C4', 'C5', 'C6', 'C7', 'T1', 'T2', 'T3', 'T4', 'T5','S1', 'S2', 'S3']
df_norm = pd.DataFrame()
for column in columns:
    df_norm[column] = normalize(df[column])
df_norm.head()

,P(IPO),P(H),P(L),P(1Day),C1,C3,C4,C5,C6,C7,T1,T2,T3,T4,T5,S1,S2,S3
0,-0.046801,-0.044305,-0.047762,-0.012133,-0.013350,0.000353,0.085376,-0.003934,-0.004315,-0.014637,0.002698,-0.000807,0.003735,0.006282,0.001049,-0.020714,-0.003360,-0.006720
1,-0.071191,-0.040601,-0.052524,-0.016119,0.052610,-0.000733,-0.080838,-0.009599,-0.023806,-0.015465,0.201091,0.184145,0.186320,0.203824,0.042886,0.008318,0.131922,0.107632
2,-0.083386,-0.010972,-0.014429,-0.016593,-0.028757,-0.000651,0.052627,-0.015232,-0.017625,-0.016070,-0.163556,-0.152817,-0.150411,-0.157234,-0.034464,-0.023940,-0.094269,-0.098902
3,-0.028508,0.003843,0.004619,-0.011685,0.028537,-0.000580,0.049916,-0.016168,-0.018814,-0.016033,-0.085065,-0.091724,-0.086955,-0.110921,-0.016562,0.037350,-0.066130,-0.040559
4,0.087346,0.040880,0.052238,0.026454,-0.033572,-0.000370,-0.165239,-0.008722,-0.009900,0.004297,0.065739,0.042225,0.040502,0.039363,0.003968,-0.004585,0.031272,0.025952

In [20]:
from sklearn import preprocessing

x = df[columns].values
scaler = preprocessing.MinMaxScaler()
x_scaled = scaler.fit_transform(x)
df_scaled = pd.DataFrame(x_scaled,columns=columns)
df_scaled.head()

,P(IPO),P(H),P(L),P(1Day),C1,C3,C4,C5,C6,C7,T1,T2,T3,T4,T5,S1,S2,S3
0,0.085366,0.070370,0.052381,0.010240,0.053924,0.169794,0.749962,0.017461,0.023948,0.001671,0.208900,0.259275,0.263014,0.284499,0.067231,0.203226,0.104978,0.131855
1,0.060976,0.074074,0.047619,0.006254,0.119884,0.168708,0.583748,0.011795,0.004457,0.000843,0.407293,0.444227,0.445600,0.482042,0.109068,0.232258,0.240260,0.246208
2,0.048780,0.103704,0.085714,0.005780,0.038517,0.168790,0.717213,0.006162,0.010637,0.000238,0.042645,0.107265,0.108869,0.120983,0.031718,0.200000,0.014069,0.039673
3,0.103659,0.118519,0.104762,0.010688,0.095811,0.168861,0.714502,0.005227,0.009448,0.000275,0.121137,0.168359,0.172324,0.167297,0.049621,0.261290,0.042208,0.098016
4,0.219512,0.155556,0.152381,0.048827,0.033702,0.169072,0.499347,0.012673,0.018362,0.020605,0.271941,0.302308,0.299782,0.317580,0.070150,0.219355,0.139610,0.164527

In [21]:
df_scaled.describe()

,P(IPO),P(H),P(L),P(1Day),C1,C3,C4,C5,C6,C7,T1,T2,T3,T4,T5,S1,S2,S3
count,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000
mean,0.132167,0.114675,0.100143,0.022373,0.067274,0.169441,0.664586,0.021395,0.028262,0.016308,0.206202,0.260082,0.259279,0.278217,0.066182,0.223940,0.108338,0.138575
std,0.073554,0.048921,0.055168,0.062148,0.072378,0.034039,0.128405,0.048686,0.059465,0.050802,0.108537,0.111009,0.110032,0.114786,0.045978,0.126025,0.091739,0.080776
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.085366,0.096296,0.076190,0.009569,0.036110,0.168896,0.583748,0.007053,0.010647,0.001351,0.135507,0.187454,0.185839,0.201560,0.045072,0.148387,0.057359,0.086348
50%,0.128049,0.114675,0.095238,0.012940,0.048146,0.169072,0.664586,0.011197,0.016579,0.004389,0.193140,0.245576,0.245472,0.264178,0.060858,0.196774,0.087121,0.126021
75%,0.170732,0.125926,0.114286,0.018142,0.068729,0.169186,0.757274,0.021406,0.027483,0.016308,0.258807,0.310670,0.312875,0.334357,0.077398,0.276613,0.131764,0.171529
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [22]:
df.head()

,I1,I2,I3,P(IPO),P(H),P(L),P(1Day),C1,C2,C3,...,C3p,C5p,C6p,Pmid,LongSentences,RealWords,LongWords,PositiveWords,NegativeWords,UncertainWords
0,AATI,ADVANCED ANALOGIC TECHNOLOGIES INC,3674,10.0,9.5,8.5,11.870000,122.0,1.0,3.43,...,1,3.864345,11.111111,9.0,0.640426,0.908876,0.054250,0.004875,0.009199,0.010929
1,ABPI,ACCENTIA BIOPHARMACEUTICALS INC,2834,8.0,10.0,8.0,7.250000,259.0,0.0,-1.62,...,0,12.028832,0.000000,9.0,0.644753,0.898724,0.051395,0.003258,0.011105,0.010876
2,ACAD,ACADIA PHARMACEUTICALS INC,2834,7.0,14.0,12.0,6.700000,90.0,1.0,-1.24,...,0,3.369134,0.000000,13.0,0.636816,0.909350,0.061764,0.011593,0.006271,0.011403
3,ACHN,ACHILLION PHARMACEUTICALS INC,2834,11.5,16.0,14.0,12.390000,209.0,1.0,-0.91,...,0,3.299697,0.000000,15.0,0.539634,0.917060,0.061630,0.009686,0.007144,0.013319
4,ACLI,AMERICAN COMMERCIAL LINES INC.,4492,21.0,21.0,19.0,56.599998,80.0,1.0,0.07,...,1,3.726269,5.000000,20.0,0.587413,0.888469,0.048550,0.004518,0.010047,0.011261

In [23]:
df.to_csv('csv_files/total_df.csv')

In [24]:
df_scaled.to_csv('csv_files/normal_data.csv')