**Importing the Datafile**

In [1]:
# import appropriate packages
import numpy as np
import pandas as pd

In [2]:
# read the IQR excel file 
dfx = pd.read_csv("../csv_files/p1iqr.csv", index_col=0)
dfx.head(10)

,C1,C3,C4,C5,C6,C7,T1,T2,T3,T4,T5,S1,S2,S3,C5p,C2,C3p
0,122.000,2.225,0.029074,40962052.0,10600000.0,51.345,470.0,12719.0,11560.0,301.0,690.0,62.0,117.0,139.0,3.864345,1.0,0
1,254.375,-1.620,-0.013352,28869196.0,2400000.0,25.936,791.0,21792.0,19585.0,510.0,1120.0,71.0,242.0,237.0,7.882541,0.0,1
2,90.000,-1.240,0.020715,16845668.0,5000000.0,7.378,201.0,5262.0,4785.0,128.0,325.0,61.0,33.0,60.0,3.369134,1.0,1
3,209.000,-0.910,0.020023,14848637.0,4500000.0,8.526,328.0,8259.0,7574.0,177.0,509.0,80.0,59.0,110.0,3.299697,1.0,1
4,80.000,0.070,-0.034895,30741716.0,8250000.0,632.298,572.0,14830.0,13176.0,336.0,720.0,67.0,149.0,167.0,3.726269,1.0,0
5,94.000,0.060,-0.057556,42402916.0,7407407.0,197.591,510.0,17999.0,13934.0,328.0,815.0,62.0,96.0,181.0,5.724394,1.0,0
6,128.000,-1.870,0.004106,19047022.0,5500000.0,5.146,495.0,15758.0,13953.0,379.0,698.0,82.0,106.0,135.0,3.463095,1.0,1
7,91.000,-0.740,0.040620,19371750.0,8000000.0,103.833,334.0,11226.0,10056.0,276.0,-1.0,55.0,120.0,122.0,2.421469,0.0,1
8,100.000,-0.510,-0.029316,52982501.0,11000000.0,279.600,620.0,14813.0,13463.0,335.0,917.0,58.0,124.0,234.0,4.816591,1.0,1
9,106.000,1.490,-0.024925,33622690.0,11000000.0,494.008,385.0,9134.0,8107.0,198.0,459.0,81.0,90.0,147.0,3.056608,1.0,0

In [3]:
# filter out binary variables 
# will concat with dfx later in the notebook 
dfbinary = dfx.filter(['C2', 'C3p'])
dfbinary.head()

    C2  C3p
0  1.0    0
1  0.0    1
2  1.0    1
3  1.0    1
4  1.0    0

In [4]:
# drop binary variable from working dataframe
dfx = dfx.drop(labels=['C2', 'C3p'], axis=1)
dfx.head()

,C1,C3,C4,C5,C6,C7,T1,T2,T3,T4,T5,S1,S2,S3,C5p
0,122.000,2.225,0.029074,40962052.0,10600000.0,51.345,470.0,12719.0,11560.0,301.0,690.0,62.0,117.0,139.0,3.864345
1,254.375,-1.620,-0.013352,28869196.0,2400000.0,25.936,791.0,21792.0,19585.0,510.0,1120.0,71.0,242.0,237.0,7.882541
2,90.000,-1.240,0.020715,16845668.0,5000000.0,7.378,201.0,5262.0,4785.0,128.0,325.0,61.0,33.0,60.0,3.369134
3,209.000,-0.910,0.020023,14848637.0,4500000.0,8.526,328.0,8259.0,7574.0,177.0,509.0,80.0,59.0,110.0,3.299697
4,80.000,0.070,-0.034895,30741716.0,8250000.0,632.298,572.0,14830.0,13176.0,336.0,720.0,67.0,149.0,167.0,3.726269

In [5]:
# checking for null values 
print(dfx.isnull().sum(axis=0).tolist())

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [6]:
# exmaining the columns datatypes and number of records 
dfx.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 682 entries, 0 to 681
Data columns (total 15 columns):
C1     682 non-null float64
C3     682 non-null float64
C4     682 non-null float64
C5     682 non-null float64
C6     682 non-null float64
C7     682 non-null float64
T1     682 non-null float64
T2     682 non-null float64
T3     682 non-null float64
T4     682 non-null float64
T5     682 non-null float64
S1     682 non-null float64
S2     682 non-null float64
S3     682 non-null float64
C5p    682 non-null float64
dtypes: float64(15)
memory usage: 85.2 KB

In [7]:
# read in y variable csv because we will be making the original variables into ratio varialbes and we need this dataframe
dfy = pd.read_csv('../csv_files/y.csv', index_col=0)
dfy.head()

   pIPO    pH    pL      p1day  Pmid  Y1  Y2        C6p
0  10.0   9.5   8.5  11.870000   9.0   0   1  11.111111
1   8.0  10.0   8.0   7.250000   9.0   1   0   0.000000
2   7.0  14.0  12.0   6.700000  13.0   1   0   0.000000
3  11.5  16.0  14.0  12.390000  15.0   1   1   0.000000
4  21.0  21.0  19.0  56.599998  20.0   0   1   5.000000

**Creating Target Variables**

In [8]:
# Define a pmid column to utilize later
def Pmid(row):
    return (row['pH'] + row['pL'])/2

# add a new column with the values returned from the previous function
dfy['Pmid'] = dfy.apply(lambda row: Pmid(row),axis=1)

In [9]:
# Define Pre-IPO Revision
def Y1Func(row):
    if row['pIPO'] < row['Pmid']:
        return 1
    return 0

# add a new column with the values returned from the previous function
dfy['Y1'] = dfy.apply(lambda row: Y1Func(row),axis=1)

In [10]:
# Define Post-IPO Initial Return
def Y2Func(row):
    if row['pIPO'] < row['p1day']:
        return 1
    return 0
# add a new column with the values returned from the previous function
dfy['Y2'] = dfy.apply(lambda row: Y2Func(row),axis=1)

**Creating Control Variables**

In [11]:
# Define Positive EPS Dummy
#def C3pFunc(row):
    #if row['C3'] > 0:
        #return 1
    #return 0
# add a new column with the values returned from the previous function
#dfx['C3p'] = dfx.apply(lambda row: C3pFunc(row),axis=1)

In [12]:
# Define Share Overhang
def C5pFunc(row):
    return row['C5']/row['C6']
    
# add a new column with the values returned from the previous function
dfx['C5p'] = dfx.apply(lambda row: C5pFunc(row),axis=1)

In [13]:
# Define Up Revision
def C6pFunc(row):
    if row['pIPO'] > row['Pmid']:
        return 100*(row['pIPO']-row['Pmid'])/row['Pmid']
    return 0
    
# add a new column with the values returned from the previous function
dfy['C6p'] = dfy.apply(lambda row: C6pFunc(row),axis=1)
dfy.head()

   pIPO    pH    pL      p1day  Pmid  Y1  Y2        C6p
0  10.0   9.5   8.5  11.870000   9.0   0   1  11.111111
1   8.0  10.0   8.0   7.250000   9.0   1   0   0.000000
2   7.0  14.0  12.0   6.700000  13.0   1   0   0.000000
3  11.5  16.0  14.0  12.390000  15.0   1   1   0.000000
4  21.0  21.0  19.0  56.599998  20.0   0   1   5.000000

**Creating Ratio Variables**

In [14]:
# Define Long Sentences
def LongSentences(row):
    return row['T4']/row['T1']
    
# add a new column with the values returned from the previous function
dfx['LongSentences'] = dfx.apply(lambda row: LongSentences(row),axis=1)

In [15]:
# Define Real Words
def RealWords(row):
    if row['T2'] == 0 :
        return 0
    else: 
        return row['T3']/row['T2']

# add a new column with the values returned from the previous function
dfx['RealWords'] = dfx.apply(lambda row: RealWords(row),axis=1)

In [16]:
# Define Long Words
def LongWords(row):
    if row['T2'] == 0 :
        return 0
    else: 
        return row['T5']/row['T2']
    
# add a new column with the values returned from the previous function
dfx['LongWords'] = dfx.apply(lambda row: LongWords(row),axis=1)

In [17]:
# Define Positive Words
def PositiveWords(row):
    if row['T2'] == 0 :
        return 0
    else: 
        return row['S1']/row['T2']
    
# add a new column with the values returned from the previous function
dfx['PositiveWords'] = dfx.apply(lambda row: PositiveWords(row),axis=1)

In [18]:
# Define Negative Words
def NegativeWords(row):
    if row['T2'] == 0 :
        return 0
    else: 
        return row['S2']/row['T2']
    
# add a new column with the values returned from the previous function
dfx['NegativeWords'] = dfx.apply(lambda row: NegativeWords(row),axis=1)

In [19]:
# Define Uncertain Words
def UncertainWords(row):
    if row['T2'] == 0 :
        return 0
    else: 
        return row['S3']/row['T2']
    
# add a new column with the values returned from the previous function
dfx['UncertainWords'] = dfx.apply(lambda row: UncertainWords(row),axis=1)

In [20]:
# gettinga sample of dfx to check that the columns were created 
dfx.sample(5)

,C1,C3,C4,C5,C6,C7,T1,T2,T3,T4,...,S1,S2,S3,C5p,LongSentences,RealWords,LongWords,PositiveWords,NegativeWords,UncertainWords
642,96.0,-2.03,-0.037223,58500000.0,8500000.0,456.000,641.0,16840.0,15571.0,403.0,...,137.0,226.0,197.0,6.882353,0.628705,0.924644,0.054929,0.008135,0.013420,0.011698
541,104.0,0.08,0.026935,33000000.0,10000000.0,4.553,317.0,9108.0,8412.0,224.0,...,29.0,110.0,164.0,3.300000,0.706625,0.923584,0.052042,0.003184,0.012077,0.018006
214,92.0,0.12,-0.039427,47917474.0,14000000.0,35.414,441.0,11236.0,9986.0,272.0,...,38.0,66.0,129.0,3.422677,0.616780,0.888750,0.052154,0.003382,0.005874,0.011481
539,81.0,1.66,-0.041773,19605358.0,7200000.0,176.269,393.0,10274.0,9022.0,224.0,...,40.0,119.0,74.0,2.722966,0.569975,0.878139,0.042243,0.003893,0.011583,0.007203
206,82.0,-0.74,0.006386,19632992.0,5000000.0,45.802,466.0,11312.0,10263.0,280.0,...,46.0,89.0,132.0,3.926598,0.600858,0.907267,0.051538,0.004066,0.007868,0.011669

**Normalizing the Data**

In [21]:
# define the function that will normalize the data 
def normalize(col):
    mean = np.mean(col)
    low = min(col)
    high = max(col)
    colnorm = (col - mean) / (high - low)
    return colnorm

In [22]:
# apply the function to the appropriate columns 
columns = ['C1', 'C3', 'C4', 'C5', 'C6', 'C7', 'T1', 'T2', 'T3', 'T4', 'T5', 
           'S1', 'S2', 'S3', 'C5p', 'LongSentences', 'RealWords', 'LongWords', 
           'PositiveWords', 'NegativeWords', 'UncertainWords']
dfx_norm = pd.DataFrame()
for column in columns:
    dfx_norm[column] = normalize(dfx[column])
dfx_norm.head()

,C1,C3,C4,C5,C6,C7,T1,T2,T3,T4,...,S1,S2,S3,C5p,LongSentences,RealWords,LongWords,PositiveWords,NegativeWords,UncertainWords
0,-0.014916,0.511558,0.124830,0.040760,0.052724,-0.229828,0.014393,0.006454,0.014527,0.018321,...,-0.028819,0.018700,-0.011087,-0.006694,0.008516,-0.002878,-0.003019,-0.003240,-0.002750,-0.003176
1,0.526772,-0.296215,-0.120852,-0.091265,-0.323348,-0.268208,0.461468,0.381713,0.377210,0.390207,...,0.033090,0.574564,0.370979,0.075493,0.011525,-0.002946,-0.003343,-0.005245,-0.001675,-0.003203
2,-0.145862,-0.216383,0.076423,-0.222532,-0.204106,-0.296238,-0.360259,-0.301967,-0.291663,-0.289509,...,-0.035697,-0.354841,-0.319079,-0.011679,0.006005,-0.002875,-0.002165,0.005092,-0.004401,-0.002933
3,0.341095,-0.147056,0.072416,-0.244335,-0.227037,-0.294504,-0.183378,-0.178011,-0.165617,-0.202320,...,0.094999,-0.239221,-0.124148,-0.012378,-0.061580,-0.002823,-0.002180,0.002727,-0.003909,-0.001954
4,-0.186783,0.058827,-0.245605,-0.070821,-0.055053,0.647673,0.156454,0.093765,0.087561,0.080598,...,0.005575,0.161001,0.098075,-0.008084,-0.028352,-0.003015,-0.003666,-0.003683,-0.002272,-0.003006

In [23]:
# import the preprocessing package from sklearn
from sklearn import preprocessing

# scale all columns to have a range of 0-1
x = dfx[columns].values
scaler = preprocessing.MinMaxScaler()
x_scaled = scaler.fit_transform(x)
dfx_scaled = pd.DataFrame(x_scaled,columns=columns)
dfx_scaled.head()

,C1,C3,C4,C5,C6,C7,T1,T2,T3,T4,...,S1,S2,S3,C5p,LongSentences,RealWords,LongWords,PositiveWords,NegativeWords,UncertainWords
0,0.458312,1.000000,0.630418,0.406884,0.462063,0.077442,0.470752,0.520721,0.522445,0.531139,...,0.433362,0.431351,0.440546,0.034399,0.441786,0.006121,0.006176,0.006161,0.003974,0.002967
1,1.000000,0.192227,0.384735,0.274860,0.085992,0.039063,0.917827,0.895980,0.885128,0.903025,...,0.495271,0.987215,0.822612,0.116586,0.444796,0.006053,0.005851,0.004156,0.005049,0.002940
2,0.327366,0.272059,0.582011,0.143592,0.205234,0.011032,0.096100,0.212300,0.216254,0.223310,...,0.426483,0.057810,0.132554,0.029414,0.439275,0.006125,0.007030,0.014493,0.002323,0.003209
3,0.814322,0.341387,0.578004,0.121790,0.182303,0.012766,0.272981,0.336256,0.342301,0.310498,...,0.557180,0.173430,0.327485,0.028715,0.371690,0.006177,0.007015,0.012129,0.002815,0.004189
4,0.286445,0.547269,0.259982,0.295303,0.354287,0.954944,0.612813,0.608032,0.595478,0.593416,...,0.467756,0.573652,0.549708,0.033009,0.404918,0.005984,0.005528,0.005718,0.004453,0.003137

In [24]:
# verify that the min and max values for each column are 0 and 1 respectively 
dfx_scaled.describe()

,C1,C3,C4,C5,C6,C7,T1,T2,T3,T4,...,S1,S2,S3,C5p,LongSentences,RealWords,LongWords,PositiveWords,NegativeWords,UncertainWords
count,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,...,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000
mean,0.473228,0.488442,0.505588,0.366124,0.409340,0.307271,0.456359,0.514267,0.507917,0.512818,...,0.462181,0.412651,0.451633,0.041094,0.433270,0.008999,0.009194,0.009401,0.006724,0.006143
std,0.253023,0.261345,0.186131,0.282736,0.273744,0.336886,0.212154,0.195646,0.191906,0.192643,...,0.211460,0.246960,0.213472,0.059783,0.057621,0.052583,0.054156,0.047612,0.053366,0.050622
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.306905,0.375000,0.384735,0.164348,0.205426,0.062589,0.305362,0.375000,0.369146,0.375000,...,0.316423,0.235686,0.288499,0.025207,0.400329,0.005954,0.005407,0.005268,0.002756,0.002280
50%,0.396931,0.534664,0.514892,0.258822,0.315244,0.156723,0.434540,0.492845,0.487419,0.491993,...,0.419604,0.355753,0.421053,0.034198,0.434512,0.006050,0.005912,0.006402,0.003641,0.003193
75%,0.584143,0.625000,0.641226,0.498609,0.523255,0.437554,0.583217,0.625000,0.621488,0.625000,...,0.589854,0.541412,0.573099,0.042698,0.464502,0.006131,0.006401,0.007766,0.004635,0.003944
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [25]:
# concat scaled dataframe with binary dataframe 
dfx = pd.concat([dfx_scaled, dfbinary], axis=1)
dfx.head()

,C1,C3,C4,C5,C6,C7,T1,T2,T3,T4,...,S3,C5p,LongSentences,RealWords,LongWords,PositiveWords,NegativeWords,UncertainWords,C2,C3p
0,0.458312,1.000000,0.630418,0.406884,0.462063,0.077442,0.470752,0.520721,0.522445,0.531139,...,0.440546,0.034399,0.441786,0.006121,0.006176,0.006161,0.003974,0.002967,1.0,0
1,1.000000,0.192227,0.384735,0.274860,0.085992,0.039063,0.917827,0.895980,0.885128,0.903025,...,0.822612,0.116586,0.444796,0.006053,0.005851,0.004156,0.005049,0.002940,0.0,1
2,0.327366,0.272059,0.582011,0.143592,0.205234,0.011032,0.096100,0.212300,0.216254,0.223310,...,0.132554,0.029414,0.439275,0.006125,0.007030,0.014493,0.002323,0.003209,1.0,1
3,0.814322,0.341387,0.578004,0.121790,0.182303,0.012766,0.272981,0.336256,0.342301,0.310498,...,0.327485,0.028715,0.371690,0.006177,0.007015,0.012129,0.002815,0.004189,1.0,1
4,0.286445,0.547269,0.259982,0.295303,0.354287,0.954944,0.612813,0.608032,0.595478,0.593416,...,0.549708,0.033009,0.404918,0.005984,0.005528,0.005718,0.004453,0.003137,1.0,0

In [26]:
# verify that new dfx dataframe has the scaled variables 
dfx.describe()

,C1,C3,C4,C5,C6,C7,T1,T2,T3,T4,...,S3,C5p,LongSentences,RealWords,LongWords,PositiveWords,NegativeWords,UncertainWords,C2,C3p
count,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,...,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000,682.000000
mean,0.473228,0.488442,0.505588,0.366124,0.409340,0.307271,0.456359,0.514267,0.507917,0.512818,...,0.451633,0.041094,0.433270,0.008999,0.009194,0.009401,0.006724,0.006143,0.863636,0.463343
std,0.253023,0.261345,0.186131,0.282736,0.273744,0.336886,0.212154,0.195646,0.191906,0.192643,...,0.213472,0.059783,0.057621,0.052583,0.054156,0.047612,0.053366,0.050622,0.343426,0.499020
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.306905,0.375000,0.384735,0.164348,0.205426,0.062589,0.305362,0.375000,0.369146,0.375000,...,0.288499,0.025207,0.400329,0.005954,0.005407,0.005268,0.002756,0.002280,1.000000,0.000000
50%,0.396931,0.534664,0.514892,0.258822,0.315244,0.156723,0.434540,0.492845,0.487419,0.491993,...,0.421053,0.034198,0.434512,0.006050,0.005912,0.006402,0.003641,0.003193,1.000000,0.000000
75%,0.584143,0.625000,0.641226,0.498609,0.523255,0.437554,0.583217,0.625000,0.621488,0.625000,...,0.573099,0.042698,0.464502,0.006131,0.006401,0.007766,0.004635,0.003944,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [27]:
dfx.to_csv('../csv_files/p1minmax.csv')